// {"plus_code": {"compound_code": "P3XV+2H2 Bournemouth, UK", "global_code": "9C2WP3XV+2H2"}, "results": [{"address_components": [Array], "formatted_address": "52 Alton Rd, Bournemouth BH10 4AF, UK", "geometry": [Object], "navigation_points": [Array], "place_id": "ChIJmUU3fCqic0gRnbPhGhyf45I", "types": [Array]}, {"address_components": [Array], "formatted_address": "3A Hood Cl, Bournemouth BH10 4DF, UK", "geometry": [Object], "navigation_points": [Array], "place_id": "ChIJV4OrZSqic0gRj2IUDvkcwFI", "plus_code": [Object], "types": [Array]}, {"address_components": [Array], "formatted_address": "8A Hood Cl, Bournemouth BH10 4DF, UK", "geometry": [Object], "navigation_points": [Array], "place_id": "ChIJV4OrZSqic0gR23_V2seDtIY", "plus_code": [Object], "types": [Array]}, {"address_components": [Array], "formatted_address": "8A Hood Cl, Bournemouth BH10 4DF, UK", "geometry": [Object], "navigation_points": [Array], "place_id": "ChIJV4OrZSqic0gR9pxvHOk7Loo", "types": [Array]}, {"address_components": [Array], "formatted_address": "1 Hood Cl, Bournemouth BH10 4DF, UK", "geometry": [Object], "place_id": "EiMxIEhvb2QgQ2wsIEJvdXJuZW1vdXRoIEJIMTAgNERGLCBVSyIaEhgKFAoSCZcwzWYqonNIEXrzpcjrYkVYEAE", "types": [Array]}, {"address_components": [Array], "formatted_address": "P3XV+2H Bournemouth, UK", "geometry": [Object], "place_id": "GhIJL4UHza5fSUARZnSby2h__r8", "plus_code": [Object], "types": [Array]}, {"address_components": [Array], "formatted_address": "1-3 Hood Cl, Bournemouth BH10 4DF, UK", "geometry": [Object], "place_id": "ChIJlzDNZiqic0gRevOlyOtiRVg", "types": [Array]}, {"address_components": [Array], "formatted_address": "Hood Cl, Bournemouth BH10 4DF, UK", "geometry": [Object], "navigation_points": [Array], "place_id": "ChIJyePiZCqic0gRr-Wd-fHUq5k", "types": [Array]}, {"address_components": [Array], "formatted_address": "Bournemouth BH10, UK", "geometry": [Object], "navigation_points": [Array], "place_id": "ChIJCd70CYChc0gRZF2KDdSq1rs", "types": [Array]}, {"address_components": [Array], "formatted_address": "Bournemouth, UK", "geometry": [Object], "place_id": "ChIJj5JVnE2fc0gR_I8DIAJXX9c", "types": [Array]}, {"address_components": [Array], "formatted_address": "Bournemouth, UK", "geometry": [Object], "place_id": "ChIJ_WegsaCYc0gRlCypaxXgLjs", "types": [Array]}, {"address_components": [Array], "formatted_address": "Bournemouth, Christchurch and Poole, UK", "geometry": [Object], "place_id": "ChIJtffK9_-hc0gRuoy3JTah6aw", "types": [Array]}, {"address_components": [Array], "formatted_address": "Bournemouth, Christchurch and Poole, UK", "geometry": [Object], "place_id": "ChIJ9_FAV3-hc0gRC-v3ThgZk2Q", "types": [Array]}, {"address_components": [Array], "formatted_address": "England, UK", "geometry": [Object], "place_id": "ChIJ39UebIqp0EcRqI4tMyWV4fQ", "types": [Array]}, {"address_components": [Array], "formatted_address": "United Kingdom", "geometry": [Object], "place_id": "ChIJqZHHQhE7WgIReiWIMkOg-MQ", "types": [Array]}], "status": "OK"}


// try {
//     const response = await Geocoder.from(userLat, userLng);
//     const formattedAddress =
//     response?.results?.[0]?.formatted_address || 'Unknown location';
//       setUserAddress(formattedAddress);

//     const { error } = await supabase
//       .from('user_profile')
//       .update({
//         user_coordinate: { lat: userLat, lng: userLng },
//         location: formattedAddress,
//       })
//       .eq('user_id', user.id);